sonar.organization=perestroika
sonar.projectKey=perestroika_bobapp-ci-cd
sonar.projectName=BobApp
sonar.sourceEncoding=UTF-8

sonar.sources=back/src/main/java,front/src
sonar.tests=back/src/test/java,front/src

sonar.exclusions=front/src/**/*.spec.ts,front/node_modules/**,front/dist/**,front/coverage/**
sonar.test.inclusions=back/src/test/**/*.java,front/src/**/*.spec.ts

sonar.java.binaries=back/target/classes
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
